spring:
  application:
    name: Managment
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/EMS
    username: postgres
    password: 1111
  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/EMS
    user: postgres
    password: 1111